### ISSUE TITLE
Error during migration run: QueryFailedError: function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by lparolari** [ondanieldev/wellets-backend#1]
I'm facing the following error while executing the step number 5 in the "How to run" section on README, i.e, `yarn run-migrations` command.

**Error and stack trace**

```
query failed: CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" varchar NOT NULL, "password" varchar NOT NULL, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))
error: error: function uuid_generate_v4() does not exist
    at Parser.parseErrorMessage (/home/lparolari/Projects/wellets-backend/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/home/lparolari/Projects/wellets-backend/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/home/lparolari/Projects/wellets-backend/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/home/lparolari/Projects/wellets-backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 207,
  severity: 'ERROR',
  code: '42883',
  detail: undefined,
  hint: 'No function matches the given name and argument types. You might need to add explicit type casts.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '621',
  routine: 'ParseFuncOrColumn'
}
```

**Solution**

Create the extension on the database.

1. start the docker with `docker-compose up -d`

2. login to the container

```
$ docker ps
docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                                       NAMES
661ea02b85eb   bitnami/postgresql:latest   "/opt/bitnami/script…"   5 seconds ago   Up 5 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   wellets-backend_postgres_1
1d68f86b57ae   bitnami/redis:latest        "/opt/bitnami/script…"   5 seconds ago   Up 5 seconds   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   wellets-backend_redis_1
$ docker exec -it 661ea02b85eb bash
I have no name!@661ea02b85eb:/$
```

3. login to postgres database

```
I have no name!@661ea02b85eb:/$ psql -U postgres
postgres=#
```

4. move to your database, i.e., the value of env variable `POSTGRES_DATABASE` (in my case, it was `wellets`)

```
postgres=# \c wellets
You are now connected to database "wellets" as user "postgres".
wellets=# 
```

5. create the "uuid-ossp" extension

```
wellets=# CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION
CREATE EXTENSION
```

Please note that in order to login as `postgres` user on docker container I had to add the `POSTGRESQL_POSTGRES_PASSWORD` environment variable under the environment variables section of postgres service in `docker-compose.yml` file:

```
...

postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=myrootpassword
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_USERNAME=wellets
      - POSTGRESQL_DATABASE=wellets

...
```

I'm sorry but I don't know how to fix this within code, so I posted the issue for in order to help other users.

**Reference**

* [Extension exists but uuid_generate_v4 fails](https://stackoverflow.com/questions/22446478/extension-exists-but-uuid-generate-v4-fails)

**Comment by lparolari** [comment]
It was just easy as that!
Thank you!
